DECLARE
D NUMBER:=:NUM1;
BEGIN CASE D
WHEN 1 THEN
DBMS_OUTPUT.PUT_LINE('SUNDAY');
WHEN 2 THEN
DBMS_OUTPUT.PUT_LINE('MONDAY');
WHEN 3 THEN
DBMS_OUTPUT.PUT_LINE('TUESDAY');
WHEN 4 THEN
DBMS_OUTPUT.PUT_LINE('WEDNESDAY');
WHEN 5 THEN
DBMS_OUTPUT.PUT_LINE('THURSDAY');
WHEN 6 THEN
DBMS_OUTPUT.PUT_LINE('FRIDAY');
WHEN 7 THEN
DBMS_OUTPUT.PUT_LINE('SATURDAY');
ELSE
DBMS_OUTPUT.PUT_LINE('INVALID DAY');
END CASE;
END;
/